#
# Module manifest for module 'Azure Active Directory Module Manifest'
#
# Generated by: Microsoft Corporation
#
# Generated on: 1/5/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Microsoft.Open.AzureAD16.Graph.PowerShell.dll'

# Version number of this module.
ModuleVersion = '2.0.0.7'

# ID used to uniquely identify this module
GUID = 'b433e830-b479-4f7f-9c80-9cc6c28e1b51'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '� 2015 Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Azure Active Directory Module'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
DotNetFrameworkVersion = '4.5'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'Amd64'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'AzureAD.Format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    'Microsoft.Open.Azure.AD.CommonLibrary.dll',
    'Microsoft.Open.AzureAD16.Graph.PowerShell.Custom.dll',
    'Microsoft.Open.AzureAD16.Graph.Client.dll',
    'Microsoft.Open.AzureADBeta.Graph.PowerShell.dll',
    'Microsoft.Open.AzureADBeta.Graph.Client.dll',
    'Microsoft.Open.MS.GraphBeta.PowerShell.dll',
	'Microsoft.Open.MS.GraphBeta.Client.dll'
)

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module  
ModuleList = @(
    'Microsoft.Open.Azure.AD.CommonLibrary.dll',
    'Microsoft.Open.AzureAD16.Graph.PowerShell.dll',
    'Microsoft.Open.AzureAD16.Graph.PowerShell.Custom.dll',
    'Microsoft.Open.AzureAD16.Graph.Client.dll',
    'Microsoft.Open.AzureADBeta.Graph.PowerShell.dll',
    'Microsoft.Open.AzureADBeta.Graph.Client.dll',
    'Microsoft.Open.MS.GraphBeta.PowerShell.dll',
	'Microsoft.Open.MS.GraphBeta.Client.dll'
) 

# List of all files packaged with this module
FileList = 'Microsoft.IdentityModel.Clients.ActiveDirectory.dll', 
           'Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll', 
           'Microsoft.Open.Azure.AD.CommonLibrary.dll', 
           'Microsoft.Open.Azure.AD.CommonLibrary.Resources.dll', 
           'Microsoft.Open.AzureAD16.Graph.PowerShell.dll',
           'Microsoft.Open.AzureAD16.Graph.PowerShell.Custom.dll',
           'Microsoft.Open.AzureAD16.Graph.Client.dll',
           'Microsoft.Open.AzureADBeta.Graph.PowerShell.dll',
           'Microsoft.Open.AzureADBeta.Graph.Client.dll',
           'Microsoft.Open.MS.GraphBeta.PowerShell.dll',
	       'Microsoft.Open.MS.GraphBeta.Client.dll',
           'Newtonsoft.Json.dll',
           'RestSharp.dll', 
           'System.IdentityModel.Tokens.Jwt.dll',               
           'System.Management.Automation.dll', 
           'Microsoft.IdentityModel.Clients.ActiveDirectory.xml', 
           'Newtonsoft.Json.xml',
           'RestSharp.xml', 
           'System.IdentityModel.Tokens.Jwt.xml'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Azure','ActiveDirectory','AzureAD', 'AD', 'AzureGraph')

        # A URL to the license for this module.
        LicenseUri = 'http://aka.ms/azps-license'

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIkFQYJKoZIhvcNAQcCoIIkBjCCJAICAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCB4pL1qFR0gfzP8
# mZTci3CIfil2XdNIe0z8NlEIPMv/maCCDY4wggYMMIID9KADAgECAhMzAAAAeAZm
# rCoRZAg+AAAAAAB4MA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMTYwNTA5MjIwNjQ0WhcNMTcwODA5MjIwNjQ0WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDjjEkx/uc8hldkxl009SWe3pOrRROfVpkFxW96tHdc3MpiCk+NrfaezAF+GIJQ
# E/HRXqeWBPmHGHhQjPe4fHaSknPvZATMmour8PedpzOYh5kpJGo/g5N7wTrhTevA
# 0qFQ8Ztsl6yPHeEfBWp8oK7vfmb2Xg0ebfLeiUVEottoYnz0DJOqbAlL3meYZyye
# MrTCFQ2TVQjEITRhhlVjNjsw0uuKigYKCe/v6XD6/3n4JgvqxwWeVZzJjql4L1wE
# HV0JUxsez6GMXdxWI0/7cZl9bUQu6b84mya0u+1WZdXWXFfkxR4fspadu7/o+Pvy
# D3U+3rq6ypE+0EhEnxM5k0wfAgMBAAGjggGLMIIBhzArBgNVHSUEJDAiBggrBgEF
# BQcDAwYKKwYBBAGCN0wIAQYKKwYBBAGCN0wTATAdBgNVHQ4EFgQUx94Wiq/BhJ9h
# vcrn+CW7rfB9pjcwUQYDVR0RBEowSKRGMEQxDTALBgNVBAsTBE1PUFIxMzAxBgNV
# BAUTKjU0ODE2K2ZiMjIwNGUzLTg0MjEtNDhkNi1hNjQ3LTllMGQ0ODJmNzdlYzAf
# BgNVHSMEGDAWgBRIbmTlUAXTgqoXNzcitW2oynUClTBUBgNVHR8ETTBLMEmgR6BF
# hkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNDb2RTaWdQ
# Q0EyMDExXzIwMTEtMDctMDguY3JsMGEGCCsGAQUFBwEBBFUwUzBRBggrBgEFBQcw
# AoZFaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNDb2RT
# aWdQQ0EyMDExXzIwMTEtMDctMDguY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcN
# AQELBQADggIBAKR7S0vtJ2GiJWqGxiajASpekSUj4YN6Bqd/zGvzEFJkonVR3IAh
# kPYH52WL8kl/JVdgg3bxPgz/NO9Nvs1jhFslTk7ZYG1BFoOz2yU98NV9uG3eD3JR
# t0tV2wl6dT9MpirfsNfnubh+EAYi1XySy+Nz7QazyUKjSljfx1tAgMmFC5qNe5VO
# PGyN2Eqp/swW2VuXGLHQoXNf1L9n9oM3xHDEh+aKgp6KvahKoXa9XGOM9GlSfSLS
# 0rZVLsOMDKu1dp9s1mYpWlj4h57L7M0OSwO5hMWYm5dAxQRUthjUazBvNv3iO1SQ
# haw/lAUo+zFrjVneUdYBj7PTJGyD5JV/wUdjeGEvsKorhNf2ykEg8Ivf6KnsSGAz
# aMojeBi/cpLQBZU0/42Jyn8xoQ2y+NPOqOsP0CcdelQXTWa46sy5qKhVAAeENyrd
# FlFwD3feiJiMPNPAGPQC15ovlUnWqIK1MxREitP4ubfghF/zdIloP9zEFTeQsKcV
# XAWinUsAjw5+HnElGhF+3kj9034qdSdxT524WvzWV5mj4wmRDMy+4tYakdz/32L/
# quBnYlpNf+4uldWIxETJjtly3Wnx8wcA+rQjLTvVIrOdXv4pzMc9emKzmHFBX7dm
# v8l5pbZDENZHPKBG0g/DKy8p/Rp0Hlc6I/mKZq2dG2gJ85mmVX7f1LPmMIIHejCC
# BWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMC
# VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
# BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJv
# b3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcN
# MjYwNzA4MjEwOTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
# bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
# aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExMIIC
# IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2
# WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSH
# fpRgJGyvnkmc6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQ
# z7NEt13YxC4Ddato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT+OPeBw3VXHml
# SSnnDb6gE3e+lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3o
# iU+EGvKhL1nkkDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6
# nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWYOUo2z3yxkq4cI6ep
# ZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf
# 28AVs70b1FVL5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF78IcV9uDjexNSTCn
# q47f7Fufr/zdsGbiwZeBe+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx
# 7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O
# 9JawvEagbJjS4NaIjAsCAwEAAaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0G
# A1UdDgQWBBRIbmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEEAYI3FAIEDB4KAFMA
# dQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAW
# gBRyLToCMZBDuRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8v
# Y3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXQy
# MDExXzIwMTFfMDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEFBQcwAoZC
# aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXQy
# MDExXzIwMTFfMDNfMjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCB
# gzA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9k
# b2NzL3ByaW1hcnljcHMuaHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABf
# AHAAbwBsAGkAYwB5AF8AcwB0AGEAdABlAG0AZQBuAHQALiAdMA0GCSqGSIb3DQEB
# CwUAA4ICAQBn8oalmOBUeRou09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LR
# bYP+vj/oCso7v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r
# 4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb
# 7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu5a8n7dDd8w6v
# mSiXmE0OPQvyCInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/
# sfQn+N4sOiBpmLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38cbxV9Rad2
# 5UAqZaPDXVJihsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUf
# FL5hYbXw3MYbBL7fQccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AAKcWx
# m6U/RXceNcbSoqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMj
# aHXmr/r8i+sLgOppO6/8MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7
# qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMTDXpQzTGCFd0wghXZ
# AgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYD
# VQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAm
# BgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTECEzMAAAB4Bmas
# KhFkCD4AAAAAAHgwDQYJYIZIAWUDBAIBBQCggcgwGQYJKoZIhvcNAQkDMQwGCisG
# AQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcN
# AQkEMSIEIIQafZ6XNq0ciGbRc2okZYYhE4AHy9Qcwy9/DZB6b2x6MFwGCisGAQQB
# gjcCAQwxTjBMoCiAJgBBAHoAdQByAGUAQQBEAFAAcgBlAHYAaQBlAHcALgBwAHMA
# ZAAxoSCAHmh0dHA6Ly93d3cuTWljcm9zb2Z0T25saW5lLmNvbTANBgkqhkiG9w0B
# AQEFAASCAQA7bKeooEPJDzfEUkMfCidh4P5hDlueAeZ0TxLjaeVotuYRX3SlLanK
# 6jZzkScvU1RsAwU5pVnE/f3+i4BocVwG6/2yLmNSmHZz9wNulpHloQAKc8hepS3A
# 9UBrYc33njBSabsjKLCC40B7IwSUVv5by3iNqZIEMYC3vOSk7oENGs2V4FVVTjuI
# FGIKfwovOrV28jXRLcdxrJbjEqvFr21U7zVWEfyPWT55BUJ2E7GcV0iHoKrsE5uN
# ngS+LhjJM8aklyk3Pd6lZ0edUSxLC6rpdml4j4VCItq9PRV5W3bJzzLbbMF9QF7j
# kQcZg7oZZkvCJa+6L6owKtiLfZ+0IXUYoYITTTCCE0kGCisGAQQBgjcDAwExghM5
# MIITNQYJKoZIhvcNAQcCoIITJjCCEyICAQMxDzANBglghkgBZQMEAgEFADCCAT0G
# CyqGSIb3DQEJEAEEoIIBLASCASgwggEkAgEBBgorBgEEAYRZCgMBMDEwDQYJYIZI
# AWUDBAIBBQAEILVmDx5JaapV1PJyxlctc0NPFjHeCLLjU+l7r1TMgQ9EAgZX4wXp
# RDEYEzIwMTYxMDA2MDAxMzAyLjU4NVowBwIBAYACAfSggbmkgbYwgbMxCzAJBgNV
# BAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4w
# HAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xDTALBgNVBAsTBE1PUFIxJzAl
# BgNVBAsTHm5DaXBoZXIgRFNFIEVTTjpCOEVDLTMwQTQtNzE0NDElMCMGA1UEAxMc
# TWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaCCDtAwggZxMIIEWaADAgECAgph
# CYEqAAAAAAACMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UE
# CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
# b2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZp
# Y2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0xMDA3MDEyMTM2NTVaFw0yNTA3MDEyMTQ2
# NTVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
# BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMIIBIjANBgkqhkiG9w0B
# AQEFAAOCAQ8AMIIBCgKCAQEAqR0NvHcRijog7PwTl/X6f2mUa3RUENWlCgCChfvt
# fGhLLF/Fw+Vhwna3PmYrW/AVUycEMR9BGxqVHc4JE458YTBZsTBED/FgiIRUQwzX
# Tbg4CLNC3ZOs1nMwVyaCo0UN0Or1R4HNvyRgMlhgRvJYR4YyhB50YWeRX4FUsc+T
# TJLBxKZd0WETbijGGvmGgLvfYfxGwScdJGcSchohiq9LZIlQYrFd/XcfPfBXday9
# ikJNQFHRD5wGPmd/9WbAA5ZEfu/QS/1u5ZrKsajyeioKMfDaTgaRtogINeh4HLDp
# mc085y9Euqf03GS9pAHBIAmTeM38vMDJRF1eFpwBBU8iTQIDAQABo4IB5jCCAeIw
# EAYJKwYBBAGCNxUBBAMCAQAwHQYDVR0OBBYEFNVjOlyKMZDzQ3t8RhvFM2hahW1V
# MBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMB
# Af8EBTADAQH/MB8GA1UdIwQYMBaAFNX2VsuP6KJcYmjRPZSQW9fOmhjEMFYGA1Ud
# HwRPME0wS6BJoEeGRWh0dHA6Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kvY3JsL3By
# b2R1Y3RzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNybDBaBggrBgEFBQcBAQRO
# MEwwSgYIKwYBBQUHMAKGPmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2Vy
# dHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3J0MIGgBgNVHSABAf8EgZUwgZIw
# gY8GCSsGAQQBgjcuAzCBgTA9BggrBgEFBQcCARYxaHR0cDovL3d3dy5taWNyb3Nv
# ZnQuY29tL1BLSS9kb2NzL0NQUy9kZWZhdWx0Lmh0bTBABggrBgEFBQcCAjA0HjIg
# HQBMAGUAZwBhAGwAXwBQAG8AbABpAGMAeQBfAFMAdABhAHQAZQBtAGUAbgB0AC4g
# HTANBgkqhkiG9w0BAQsFAAOCAgEAB+aIUQ3ixuCYP4FxAz2do6Ehb7Prpsz1Mb7P
# BeKp/vpXbRkws8LFZslq3/Xn8Hi9x6ieJeP5vO1rVFcIK1GCRBL7uVOMzPRgEop2
# zEBAQZvcXBf/XPleFzWYJFZLdO9CEMivv3/Gf/I3fVo/HPKZeUqRUgCvOA8X9S95
# gWXZqbVr5MfO9sp6AG9LMEQkIjzP7QOllo9ZKby2/QThcJ8ySif9Va8v/rbljjO7
# Yl+a21dA6fHOmWaQjP9qYn/dxUoLkSbiOewZSnFjnXshbcOco6I8+n99lmqQeKZt
# 0uGc+R38ONiU9MalCpaGpL2eGq4EQoO4tYCbIjggtSXlZOz39L9+Y1klD3ouOVd2
# onGqBooPiRa6YacRy5rYDkeagMXQzafQ732D8OE7cQnfXXSYIghh2rBQHm+98eEA
# 3+cxB6STOvdlR3jo+KhIq/fecn5ha293qYHLpwmsObvsxsvYgrRyzR30uIUBHoD7
# G4kqVDmyW9rIDVWZeodzOwjmmC3qjeAzLhIp9cAvVCch98isTtoouLGp25ayp0Ki
# yc8ZQU3ghvkqmqMRZjDTu3QyS99je/WZii8bxyGvWbWu3EQ8l1Bx16HSxVXjad5X
# wdHeMMD9zOZN+w2/XU/pnR4ZOC+8z1gFLu8NoFA12u8JJxzVs341Hgi62jbb01+P
# 3nSISRIwggTaMIIDwqADAgECAhMzAAAAmGI6XizSVvCqAAAAAACYMA0GCSqGSIb3
# DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYD
# VQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAk
# BgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTE2MDQyNzE3
# MDYxOFoXDTE3MDcyNzE3MDYxOFowgbMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
# YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQg
# Q29ycG9yYXRpb24xDTALBgNVBAsTBE1PUFIxJzAlBgNVBAsTHm5DaXBoZXIgRFNF
# IEVTTjpCOEVDLTMwQTQtNzE0NDElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3Rh
# bXAgU2VydmljZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOAOuK45
# scg7wT9vH5pj6Jn7PY1U41prMkzb3DV8AM4eY1lPxbj+9ElRumPR0l8QlMmNQGsd
# +QFq/YAmZ8KhMilqyVcGWgyXZEdbzNM+BNTlOWPfltrEyf45AhY1tJNxRYYIccka
# e1tkoXsxOUqCMfdJDojTmGEVHUoNe4bNtcSnai/r0f8TNZkahsZeQ/ogAG7LAer5
# UiDLf2vn943M8gb6/n512fwG+7B+kIpuFICyN//Shb8V91eO9XoLqKLhILJnS9Iy
# 6l+nWtqVIn48oe0MOHZhiM4fUzdP5AwRRylvlQUABIYeAHDhJOrwB35zIURiC5sA
# T/QSz65pX7UNmJUCAwEAAaOCARswggEXMB0GA1UdDgQWBBQXwQiX7fZoeNFl+EN1
# l6+Kpah+fTAfBgNVHSMEGDAWgBTVYzpcijGQ80N7fEYbxTNoWoVtVTBWBgNVHR8E
# TzBNMEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9k
# dWN0cy9NaWNUaW1TdGFQQ0FfMjAxMC0wNy0wMS5jcmwwWgYIKwYBBQUHAQEETjBM
# MEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRz
# L01pY1RpbVN0YVBDQV8yMDEwLTA3LTAxLmNydDAMBgNVHRMBAf8EAjAAMBMGA1Ud
# JQQMMAoGCCsGAQUFBwMIMA0GCSqGSIb3DQEBCwUAA4IBAQAMPogYsXQ/7uQtdYzz
# kXA9kNHSWzVnZJq/WeZAbGADBN3qnB3+Nv8qRVA1y9wyaLm4hLOZAWxy41uM9yDn
# 7pRMML0JL2bmpVwXJ2tVYfTIZABATMaJSWQ2QNS+zZ1mVTjCPpInfoJSIzDx7a6E
# icO03LHKzFbyGMuIUImuvLEBFQ1+a33YQRIsVSSdwUAueILP9N+xHvNytzqbWDKQ
# EtvAb2hJ8g1USVzEODnKUWIoV4hhWneWB4wQ7AFROHP7SK65YyFlAtu5GAP4swhi
# gCEKvnvPC0Pkpwkq5UvMg+ArJBnfTg85FCafH11n64meqfDRWH4fS9KTWn8PBwk+
# JIPyoYIDeTCCAmECAQEwgeOhgbmkgbYwgbMxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
# EwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
# ZnQgQ29ycG9yYXRpb24xDTALBgNVBAsTBE1PUFIxJzAlBgNVBAsTHm5DaXBoZXIg
# RFNFIEVTTjpCOEVDLTMwQTQtNzE0NDElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUt
# U3RhbXAgU2VydmljZaIlCgEBMAkGBSsOAwIaBQADFQCYV3Pt6yEi3m5YrsgazVMO
# 9Q0FfqCBwjCBv6SBvDCBuTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
# b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
# dGlvbjENMAsGA1UECxMETU9QUjEnMCUGA1UECxMebkNpcGhlciBOVFMgRVNOOjU3
# RjYtQzFFMC01NTRDMSswKQYDVQQDEyJNaWNyb3NvZnQgVGltZSBTb3VyY2UgTWFz
# dGVyIENsb2NrMA0GCSqGSIb3DQEBBQUAAgUA25+vhDAiGA8yMDE2MTAwNTE2NTc0
# MFoYDzIwMTYxMDA2MTY1NzQwWjB3MD0GCisGAQQBhFkKBAExLzAtMAoCBQDbn6+E
# AgEAMAoCAQACAgEMAgH/MAcCAQACAhe7MAoCBQDboQEEAgEAMDYGCisGAQQBhFkK
# BAIxKDAmMAwGCisGAQQBhFkKAwGgCjAIAgEAAgMW42ChCjAIAgEAAgMHoSAwDQYJ
# KoZIhvcNAQEFBQADggEBAFORwfCfp5mezD5orBTo0o/xsLjUld6QdxycCAHxXGvd
# /kM/uJ2qIpSPcsbS6WxOtzWs6wQ2h5L67njzemRG4FCQdqt3Dz//nerUQdbFoghn
# V0M+rut33moH0+LAkerGpCgGzmrH9jMh0Iw1tVxe9z6HYUJ5nP7wH3w++7xO40ya
# 1VTs6fMhipxCovr2Zkf9KEWc2qxtlnyAzCbvWbvdxS+qMtoLot8WpbTL+UQZukw0
# JLzx+54lbZCuVzPuIqX3y3tTc5SGsnnmHyEnf25LyFoy49JCZWRuKB0OOOYpD53/
# L4bYrrYDD77B2Pmv7DMtojKMR0T1QZ25K2e31LQnaD8xggL1MIIC8QIBATCBkzB8
# MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
# bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
# aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAJhiOl4s0lbwqgAAAAAA
# mDANBglghkgBZQMEAgEFAKCCATIwGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEE
# MC8GCSqGSIb3DQEJBDEiBCAQJDl1sqBp+eqjhF2w0r8WaUlqPNMgL2pK91elUyhG
# 1jCB4gYLKoZIhvcNAQkQAgwxgdIwgc8wgcwwgbEEFJhXc+3rISLebliuyBrNUw71
# DQV+MIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAACY
# YjpeLNJW8KoAAAAAAJgwFgQUEnWCsIDvNHdo6ffCGhgSNlS6Lr4wDQYJKoZIhvcN
# AQELBQAEggEAzwamFMEjXnPbzLA81eIPzTLfcEwdGiErCSIfTd6aRw8K2ejSE0KE
# G7GNgh6/f4x5GssKjgJCN9nv3yMxZr5omLGSQnBUej+U0QifPYI5cupfw0OvypZK
# 19Ud0Gcbap28vgt9tGi4Qhmp917HAeDQ0t8XHPQ3/P2iefEPWfd0oJGPiNgC65dU
# VAVdyE89GoeTwEhkks3sAC8QyZNjmDPn/fhCVBYOPI3ZoiPs7zZviQGnhrEdege9
# T0TMZfWIwdj+0RAZUPvgD5KIXrLfnd9FvNBUJUpbHoXSSJXQNOtkWgrZuD2/lrS2
# mfbqTXKOX0JNT5vd0RLgSoQ+IBjhwiN36g==
# SIG # End signature block
