dfsrdiag backlog /rgname:Alta /rfname:Comun /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Alta /rfname:Comercial /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Alta /rfname:"Direccion RRHH" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
##/////////////////
dfsrdiag backlog /rgname:Alta2 /rfname:"Info Corporativo" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Alta2 /rfname:"Info Operacion" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Alta2 /rfname:SGC /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
##/////////////////
dfsrdiag backlog /rgname:Media /rfname:Abastecimiento /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:Chivornet /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:Extranet /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Gerencia de desarrollo" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Gerencia General" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Info Almacen" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Info Gestion de proyectos" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Info Gestion y Desempeno" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Info Mantenimiento" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Info MCH" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Info Obras Civiles" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Info Predios" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Info RCM2" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Info Recursos Humanos" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Info Seguridad industrial" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Info Taller Electrico" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Info Taller Electronico" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"Info Taller Industrial" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:Legal /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:"PCH Tunjita" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:Sistemas /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Media /rfname:Tecnologia /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
##/////////////////
dfsrdiag backlog /rgname:Baja /rfname:"Control interno SBU" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Baja /rfname:"Entrega Control Interno" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Baja /rfname:Facturacion /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Baja /rfname:"Informe Manto Chivor II" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Baja /rfname:"Migracion Correo" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Baja /rfname:"Politicas SBU Andes" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Baja /rfname:SAPLogon /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Baja /rfname:"Seguridad Fisica Recepcion" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v
dfsrdiag backlog /rgname:Baja /rfname:"Servicios Generales y Ambiental" /smem:chv00dfs01pr /rmem:chv01dfs00pr /v


dfsrdiag backlog /rgname:Media /smem:chv00dfs01pr /rmem:chv01dfs00pr /v


